title: "Creatify"
description: "Creatify is a digital agency crafting mobile, web, and brand experiences that help businesses grow."
images:
  - "images/home/features/feature-1.webp"

# logo: "images/shared/logo.png"

favicons:
  themeColor: "#FFFFFF"
  backgroundColor: "#FFFFFF"
  faviconColor: "#000000"

contact:
  - "Support.creatify@gmail.com"
  - "+92-3166710837"

social:
  instagram: "https://www.instagram.com/creatify.site"
  facebook: "https://www.facebook.com/creatify"
  linkedin: "https://www.linkedin.com/in/creatify-site/"
  github: "https://github.com/creatify-site"

copyright: "© 2026 Creatify. All Rights Reserved"
