title: "Creatify"
description: "Creatify is a digital agency crafting mobile, web, and brand experiences that help businesses grow."
images:
  - "images/home/features/feature-1.webp"

# logo: "images/shared/logo.png"

favicons:
  themeColor: "#FFFFFF"
  backgroundColor: "#FFFFFF"
  faviconColor: "#000000"

contact:
  - "Support.creatify@gmail.com"
  - "0316-6710837"

social:
  instagram: "creatify.site"
  facebook: "creatify"

copyright: "© 2026 Creatify. All Rights Reserved"
